[tool.poetry]
name = "intel-data-analysis"
version = "0.1.0"
description = ""
authors = ["Danil <truxin.daniil@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"
spacy = "^3.8.3"
jupyter = "^1.1.1"
numpy = "^2.2.1"
pandas = "^2.2.3"
matplotlib = "^3.10.0"
seaborn = "^0.13.2"
scipy = "^1.14.1"
graphviz = "^0.20.3"
selenium = "^4.27.1"
scikit-learn = "^1.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
